import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Footer } from '../component/Footer'
import { Links } from '../component/Links'
import { Headline } from '../component/Headline'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>AboutPage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Headline page="about"/>
        <Links />
      </main>
      <Footer />
    </div>
  )
}
