import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Footer } from '../component/Footer'
import { Main } from '../component/Main'
import { Header } from '../component/Header'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>AboutPage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main page="about"/>
      <Footer />
    </div>
  )
}
