import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { Header } from "../../components/Header";
import React from "react";
import { useRouter } from "next/router";

const PostId = () => {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>{router.query.id} </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>{router.query.id}</div>
      <Header />
    </div>
  );
};

export default PostId;
