import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { Header } from "../../components/Header";
import React from "react";
import useSWR from "swr";

const PostId = () => {
  const fetcher = async (url) => {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error("エラーが発生したため、データの取得に失敗しました");
    }

    const json = await response.json();
    return json;
  };

  const { data, error } = useSWR(
    "https://jsonplaceholder.typicode.com/posts/1",
    fetcher
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>{data?.title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <h1>{data?.title}</h1>
        <p>{data?.body}</p>
      </div>
      <Header />
    </div>
  );
};

export default PostId;
