import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Main } from "../components/Main";
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";
import React from "react";

const About = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>AboutPage</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />

      {props.isShow ? <h1>{props.doubleCount}</h1> : true}
      <button onClick={props.handleClick}>ボタン</button>
      <button onClick={props.handleDisplay}>
        {props.isShow ? "非表示" : "表示"}
      </button>

      <input type="text" value={props.text} onChange={props.handleChange} />
      <button onClick={props.handleAdd}>追加</button>
      <ul>
        {props.array.map((item) => {
          return <li key={item}>{item}</li>;
        })}
      </ul>

      <Main page="about" />
      <Footer />
    </div>
  );
};

export default About;
