import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Header } from "../components/Header";
import { Posts } from "../components/Posts";
import React, { useCallback, useEffect, useState } from "react";

const Home = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>IndexPage</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Posts />
    </div>
  );
};

export default Home;
