import Head from "next/head";
import { PostList } from "src/components/Post/PostList";
import React from "react";

const Posts = () => {
  return (
    <div>
      <Head>
        <title>PostsPage</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <PostList />
    </div>
  );
};

export default Posts;
